import { chromium } from "playwright";
const url = process.argv[2] ?? "https://morcoan.github.io/crosstalk/";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
await p.goto(url);
await p.waitForSelector(".mission-card");
const overflow = await p.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
if (overflow > 1) throw new Error(`mobile layout overflows by ${overflow}px`);
await p.click('[data-role="btn-utility"]');
await p.waitForSelector('.hud.is-utilities-open [data-role="btn-manual"]', { state: "visible" });
await p.click('[data-role="btn-utility"]');
await p.screenshot({ path: "scripts/shots/mobile-menu.png", fullPage: true });
await p.click(".mission-card:nth-child(2)");
await p.waitForSelector(".btn-arm");
await p.click(".btn-arm");
await p.waitForTimeout(800);
const timerTop = await p.locator(".devbar").evaluate((el) => el.getBoundingClientRect().top);
if (timerTop < 55 || timerTop > 70) throw new Error(`sticky device bar is misplaced at ${timerTop}px`);
await p.screenshot({ path: "scripts/shots/mobile-device.png", fullPage: true });
await b.close();
console.log(`mobile UX + shots passed at ${url}`);
