import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
await p.goto("https://morcoan.github.io/crosstalk/");
await p.waitForSelector(".mission-card");
await p.screenshot({ path: "scripts/shots/mobile-menu.png", fullPage: true });
await p.click(".mission-card:nth-child(2)");
await p.waitForSelector(".btn-arm");
await p.click(".btn-arm");
await p.waitForTimeout(800);
await p.screenshot({ path: "scripts/shots/mobile-device.png", fullPage: true });
await b.close();
console.log("mobile shots saved");
